pipeline:
  build:
    image: ruby
    commands:
      - bundle install
      - bundle exec rake spec
  notify:
    image: plugins/slack
    channel: home_wifi_backend
    username: javier.juarez@fon.com

