pipeline:
  build:
    image: ruby
    commands:
      - bundle install
      - bundle exec rake spec
      - bundle exec rake build
    volumes:
      - $(pwd):/module
  notify:
    image: plugins/slack
    channel: home_wifi_backend
    username: javier.juarez@fon.com

